### ISSUE TITLE
Compling my own iteration.

### ISSUE THREAD

**Issue by iDump-ster** [KleskBY/DeadByDaylightBot#1]
The Wiggle doesnt work, so I need to change the values on lines 306, and 311 of DBD.cpp to '0x1F', for S.
However im having a bit of an issue complining my own.

**Comment by tgd0118** [comment]
How can I use it?
[DeadByDaylightBot-master.zip](https://github.com/KleskBY/DeadByDaylightBot/files/4088347/DeadByDaylightBot-master.zip)

**Comment by iDump-ster** [comment]
You'd have to open a project on visual studio, and compile into an executable, or just download the executable.
A post on a forum from this person :[Here](https://www.unknowncheats.me/forum/other-games/368540-dead-daylight-script.html)
I managed to make the alteration that I needed, cause my hotkeys are weird. However for the average player with these binds, just downloading the executable will just be simpler.
